name: Nightly builds
on:
  schedule:
    - cron: '0 0 * * *' # Run at 12 AM UTC.
  workflow_dispatch:

permissions: {}

jobs:
  build:
    if: github.repository_owner == 'woocommerce'
    name: Nightly builds
    strategy:
      fail-fast: false
      matrix:
        build: [trunk]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.build }}

      - name: Setup WooCommerce Monorepo
        uses: ./.github/actions/setup-woocommerce-monorepo
        with:
          build: false

      - name: Build zip
        working-directory: plugins/woocommerce
        run: bash bin/build-zip.sh

      - name: Deploy nightly build
        uses: WebFreak001/deploy-nightly@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/25945111/assets{?name,label}
          release_id: 25945111
          asset_path: plugins/woocommerce/woocommerce.zip
          asset_name: woocommerce-${{ matrix.build }}-nightly.zip
          asset_content_type: application/zip
          max_releases: 1
  update:
    name: Update nightly tag commit ref
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Update nightly tag
        uses: richardsimko/github-tag-action@v1.0.5
        with:
          tag_name: nightly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
