name: Run lint checks potentially affecting projects across the monorepo
on:
    pull_request:
        branches:
            - 'trunk'
concurrency:
    group: changelogger-${{ github.event_name }}-${{ github.ref }}
    cancel-in-progress: true

permissions: {}

jobs:
    changelogger_used:
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.user.login != 'github-actions[bot]' }}
        name: Changelogger use
        runs-on: ubuntu-20.04
        permissions:
            contents: read
        timeout-minutes: 15
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  fetch-depth: 0

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo
              with:
                  build: false

            - name: Check change files are touched for touched projects
              env:
                  BASE: ${{ github.event.pull_request.base.sha }}
                  HEAD: ${{ github.event.pull_request.head.sha }}
              run: php tools/monorepo/check-changelogger-use.php --debug "$BASE" "$HEAD"

            - name: Run changelog validation
              run: pnpm run -r changelog validate
