name: Prepare package release
on:
    workflow_dispatch:
        inputs:
            packages:
                description: 'Enter a specific package to release, or packages separated by commas, ie @woocommerce/components,@woocommerce/number. Leaving this input to the default "-a" will prepare to release all eligible packages. When releasing a package for the first time, pass the "--initialRelease" flag.'
                required: false
                default: '-a'

permissions: {}

jobs:
    prepare:
        name: Run prepare script
        runs-on: ubuntu-20.04
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v3

            - name: Setup WooCommerce Monorepo
              uses: ./.github/actions/setup-woocommerce-monorepo

            - name: Execute script
              run: ./tools/package-release/bin/dev prepare ${{ github.event.inputs.packages }}

            - name: Print git status
              run: git status

            - name: Get current date
              id: date
              run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

            - name: Set all package string
              id: all_description
              if: ${{ github.event.inputs.packages == '-a'}}
              run: echo "str=all packages" >> $GITHUB_OUTPUT

            - name: Set Specific packages string
              id: specific_description
              if: ${{ github.event.inputs.packages != '-a'}}
              run: echo "str=${{ github.event.inputs.packages }}" >> $GITHUB_OUTPUT

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: 'Automated change: Prep ${{ steps.all_description.outputs.str || steps.specific_description.outputs.str }} for release.'
                  branch: release/packages-${{ steps.date.outputs.date }}
                  delete-branch: true
                  title: Prepare Packages for Release
                  reviewers: ${{ github.actor }}
                  body: |
                      # Prepare ${{ steps.all_description.outputs.str || steps.specific_description.outputs.str }} for release.
                      This PR has been autogenerated by [Prepare Package Release workflow](https://github.com/woocommerce/woocommerce/actions/workflows/prepare-package-release.yml) in run [${{ github.run_id }}](https://github.com/woocommerce/woocommerce/actions/runs/${{ github.run_id }})
