name: Check daily smoke test site status.
on:
  schedule:
    - cron: '25 7 * * *'

permissions: {}

jobs:
  ping_site:
    runs-on: ubuntu-20.04
    name: Check site and notify if not found
    steps:
    - name: Check site status
      id: sitecheck
      uses: srt32/uptime@958231f4d95c117f08eb0fc70907e80d0dfedf2b
      with:
        url-to-hit: "${{ secrets.SMOKE_TEST_URL }}ready/"
        expected-statuses: "200,301"
    - name: Send message to Slack API
      if: failure()
      uses: archive/github-actions-slack@deecc2edc496dc642d643de1d7cf3a47f51fb27a
      id: notify
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SMOKE_TEST_SLACK_TOKEN }}
        slack-channel: ${{ secrets.SMOKE_TEST_SLACK_CHANNEL }}
        slack-text: ':warning: <!subteam^${{ secrets.SMOKE_TEST_SLACK_GROUP }}> FYI the URL ${{ secrets.SMOKE_TEST_URL }}ready/ appears to be returning `404 not found` :x:'
